// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naqabgtjrsuqqulkyota.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcWFiZ3RqcnN1cXF1bGt5b3RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDczNjksImV4cCI6MjA2Nzc4MzM2OX0.y43hNbMr689pgsiV_CcZ3oxZ8tyBfhc35UEjEPqV_ZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});